#!/bin/sh

case "$1" in
	vim)
		cd vim/
		./configure --prefix=$HOME/.local
		make
		make install
		;;
	curl)
		cd curl/
		./buildconf
		./configure --prefix=$HOME/.local
		make
		make install
		;;
	git)
		cd git/
		CPPFLAGS="-I $HOME/.local/include" LDFLAGS="-L$HOME/.local/lib" ./configure --prefix=$HOME/.local
		make
		make install
		;;
	*)
		echo You must specify a valid argument.
		;;
esac
