#!/bin/sh

INSTALL_LOCATION=$HOME/.local
SOURCES=`pwd`

install_vim () {
	cd $SOURCES/vim/
	./configure --prefix=$INSTALL_LOCATION
	make
	make install
}

install_curl () {
	cd $SOURCES/curl/
	./buildconf
	./configure --prefix=$INSTALL_LOCATION
	make
	make install
}

# curl is a dependency
install_git () {
	cd $SOURCES/git/
	CPPFLAGS="-I $INSTALL_LOCATION/include" LDFLAGS="-L$INSTALL_LOCATION/lib" ./configure --prefix=$INSTALL_LOCATION
	make
	make install
}

case "$1" in
	all)
		install_vim
		install_curl
		install_git
		;;
	vim)
		install_vim
		;;
	curl)
		install_curl
		;;
	git)
		install_git
		;;
	*)
		echo You must specify a valid argument.
		;;
esac
